// <auto-generated />
namespace PayrollManagementDL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class keyupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keyupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202310110257503_key update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
